version: '2'
services:
  prometheus:
    image: prom/prometheus
    ports:
      - '9090:9090'
    container_name: prometheus
    restart: unless-stopped
    network: 
      - promegraf
    volumes:
      - '/prometheus.yml:/etc/prometheus/prometheus.yml'
  grafana:
    image: grafana/grafana
    ports:
      - '3000:3000'
    container_name: grafana
    restart: unless-stopped
    network: 
      - promegraf
    depends_on:
      - prometheus
    volumes:
      - '/grafana.ini:/etc/grafana/grafana.ini'
networks:
  promegraf:
